version: "3"

networks:
  uu_net:
    driver: ${NETWORKS_DRIVER}

services:
  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    build:
      context: ./services/nginx
      args:
        NGINX_IMAGE_TAG: ${NGINX_IMAGE_TAG}
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./code:/code/:rw
      - ./services/nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ./services/nginx/conf/vhost:/etc/nginx/vhost:rw
      - ./services/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    stdin_open: true
    tty: true
    restart: always
    networks:
      - uu_net

  mysql:
    container_name: ${CONTAINER_PREFIX}_mysql
    build:
      context: ./services/mysql
      args:
        MYSQL_IMAGE_TAG: ${MYSQL_IMAGE_TAG}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ./services/mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ./services/mysql/data:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${MYSQL_TIMEZONE}"
    networks:
      - uu_net

  redis:
    container_name: ${CONTAINER_PREFIX}_redis
    build:
      context: ./services/redis
      args:
        REDIS_IMAGE_TAG: ${REDIS_IMAGE_TAG}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ./services/redis/conf/redis.conf:/etc/redis.conf:rw
      - ./services/redis/data:/data:rw
    restart: always
    stdin_open: true
    tty: true
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - uu_net

  rabbitmq:
    container_name: ${CONTAINER_PREFIX}_rabbitmq
    build:
      context: ./services/rabbitmq
      args:
        RABBITMQ_IMAGE_TAG: ${RABBITMQ_IMAGE_TAG}
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_D}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - ./services/rabbitmq/data:/var/lib/rabbitmq:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - uu_net

  php:
    container_name: ${CONTAINER_PREFIX}_php
    build:
      context: ./services/php
      args:
        PHP_IMAGE_TAG: ${PHP_IMAGE_TAG}
    ports:
      - "${PHP_FPM_PORT}:9000"
      - "${PHP_SWOOLE_PORT_A}:9501"
      - "${PHP_SWOOLE_PORT_B}:9502"
    volumes:
      - ./code:/code/:rw
      - ./services/php/conf/${PHP_VERSION_TAG}/php.ini:/etc/${PHP_VERSION_TAG}/php.ini:ro
      - ./services/php/conf/${PHP_VERSION_TAG}/php-fpm.d:/etc/${PHP_VERSION_TAG}/php-fpm.d:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - uu_net
